<?php

	/**
	 * Create options sub pages
	 */

	if ( function_exists('acf_add_options_sub_page') ) {

		acf_add_options_sub_page('Contact Details');
		acf_add_options_sub_page('General');
		acf_add_options_sub_page('Shop');

	}
	
	/**
	 * ACF register field groups - used for backup
	 * 
	 * @fieldgroup	Main Template
	 * @fieldgroup	Content Page Template
	 * @fieldgroup	Page Attributes
	 * @fieldgroup	Featured Image
	 * @fieldgroup	Event Attributes
	 * @fieldgroup	Event Category Attributes
	 * @fieldgroup	Product Category Attributes
	 * @fieldgroup	Product Badge Attributes
	 * @fieldgroup	Shop - About
	 * @fieldgroup	Shop - Why Shop With Us
	 * @fieldgroup	Contact Details Options
	 * @fieldgroup	General Options
	 * @fieldgroup	Shop Options
	 */
	/*
	if(function_exists("register_field_group"))
	{
		register_field_group(array (
			'id' => 'acf_main-template',
			'title' => 'Main Template',
			'fields' => array (
				array (
					'key' => 'field_533d351f8e073',
					'label' => 'Main Template Layouts',
					'name' => 'acf-main_template_layouts',
					'type' => 'flexible_content',
					'instructions' => 'Add "Featured Links" layout in order to display Contact Details box',
					'layouts' => array (
						array (
							'label' => 'Banner',
							'name' => 'banner',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
							),
						),
						array (
							'label' => 'Slider',
							'name' => 'slider',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_533d36598e076',
									'label' => 'Layout Title',
									'name' => 'layout_title',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
								),
								array (
									'key' => 'field_533d368b8e077',
									'label' => 'Sort Title',
									'name' => 'sort_title',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
								),
							),
						),
						array (
							'label' => 'Featured Links',
							'name' => 'featured_links',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_533d374f8e079',
									'label' => 'Links',
									'name' => 'links',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_533d37f98e07b',
											'label' => 'Title',
											'name' => 'title',
											'type' => 'text',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_533d38128e07c',
											'label' => 'Description',
											'name' => 'description',
											'type' => 'textarea',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => 2,
											'formatting' => 'br',
										),
										array (
											'key' => 'field_533d389d8e07d',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => 'Image dimensions: 790x200px',
											'column_width' => '',
											'save_format' => 'object',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_533d39278e07e',
											'label' => 'Internal Link',
											'name' => 'internal_link',
											'type' => 'page_link',
											'column_width' => '',
											'post_type' => array (
												0 => 'post',
												1 => 'page',
												2 => 'event',
											),
											'allow_null' => 1,
											'multiple' => 0,
										),
										array (
											'key' => 'field_533d399a8e07f',
											'label' => 'External Link',
											'name' => 'external_link',
											'type' => 'text',
											'column_width' => '',
											'default_value' => '',
											'placeholder' => 'http://',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'row',
									'button_label' => 'Add Featured Link',
								),
							),
						),
					),
					'button_label' => 'Add Layout',
					'min' => '',
					'max' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-templates/main.php',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 1,
		));
		register_field_group(array (
			'id' => 'acf_content-page-template',
			'title' => 'Content Page Template',
			'fields' => array (
				array (
					'key' => 'field_53943c488056c',
					'label' => 'Content Page Template Layouts',
					'name' => 'acf-content_page_template_layouts',
					'type' => 'flexible_content',
					'layouts' => array (
						array (
							'label' => 'Content Row',
							'name' => 'content_row',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_53943ccb8056d',
									'label' => 'Content Columns',
									'name' => 'content_columns',
									'type' => 'repeater',
									'instructions' => 'Total columns width must be equal or less than 1. You may define 3 columns at the most',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_53943da18056e',
											'label' => 'Width',
											'name' => 'width',
											'type' => 'select',
											'required' => 1,
											'column_width' => 15,
											'choices' => array (
												4 => '1/3',
												6 => '1/2',
												8 => '2/3',
												12 => 1,
											),
											'default_value' => 12,
											'allow_null' => 0,
											'multiple' => 0,
										),
										array (
											'key' => 'field_53943e138056f',
											'label' => 'Title',
											'name' => 'title',
											'type' => 'text',
											'column_width' => 25,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_53943e2c80570',
											'label' => 'Content',
											'name' => 'content',
											'type' => 'wysiwyg',
											'column_width' => 60,
											'default_value' => '',
											'toolbar' => 'full',
											'media_upload' => 'yes',
										),
									),
									'row_min' => '',
									'row_limit' => 3,
									'layout' => 'row',
									'button_label' => 'Add Column',
								),
							),
						),
						array (
							'label' => 'FAQs',
							'name' => 'faqs',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_53956ec637d62',
									'label' => 'FAQs List',
									'name' => 'faqs_list',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5395729d37d63',
											'label' => 'Question',
											'name' => 'question',
											'type' => 'text',
											'required' => 1,
											'column_width' => 40,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_539572ce37d64',
											'label' => 'Answer',
											'name' => 'answer',
											'type' => 'wysiwyg',
											'required' => 1,
											'column_width' => 60,
											'default_value' => '',
											'toolbar' => 'full',
											'media_upload' => 'yes',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'table',
									'button_label' => 'Add Question',
								),
							),
						),
						array (
							'label' => 'Excerpts',
							'name' => 'excerpts',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_53958586c08a7',
									'label' => 'Excerpts List',
									'name' => 'excerpts_list',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5395867ac08aa',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => 'Image Dimensions: 190x190px',
											'column_width' => 20,
											'save_format' => 'object',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_539585e7c08a8',
											'label' => 'Title',
											'name' => 'title',
											'type' => 'text',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_53958614c08a9',
											'label' => 'Excerpt',
											'name' => 'excerpt',
											'type' => 'wysiwyg',
											'column_width' => 60,
											'default_value' => '',
											'toolbar' => 'basic',
											'media_upload' => 'no',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'table',
									'button_label' => 'Add Excerpt',
								),
							),
						),
						array (
							'label' => 'Contacts',
							'name' => 'contacts',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5395a439a3d85',
									'label' => 'Contacts List',
									'name' => 'contacts_list',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5395a45ea3d86',
											'label' => 'Role',
											'name' => 'role',
											'type' => 'text',
											'required' => 1,
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5395a481a3d87',
											'label' => 'Name',
											'name' => 'name',
											'type' => 'text',
											'required' => 1,
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5395a48da3d88',
											'label' => 'Phone',
											'name' => 'phone',
											'type' => 'text',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5395a4a5a3d89',
											'label' => 'Email',
											'name' => 'email',
											'type' => 'email',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array (
											'key' => 'field_53ac17812145b',
											'label' => 'Address',
											'name' => 'address',
											'type' => 'textarea',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => 2,
											'formatting' => 'br',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'table',
									'button_label' => 'Add Contact',
								),
							),
						),
					),
					'button_label' => 'Add Layout',
					'min' => '',
					'max' => '',
				),
				array (
					'key' => 'field_5396e9c1c8292',
					'label' => 'Content Page Template Widgets Area',
					'name' => 'acf-content_page_template_widgets_area',
					'type' => 'flexible_content',
					'layouts' => array (
						array (
							'label' => 'Languages',
							'name' => 'languages',
							'display' => 'row',
							'min' => '',
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_5396eaafc8293',
									'label' => 'Languages List',
									'name' => 'languages_list',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5396eb1ec8294',
											'label' => 'Country Code',
											'name' => 'country_code',
											'type' => 'text',
											'instructions' => '2 digit country code',
											'column_width' => 25,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_53984a460d256',
											'label' => 'Language Name',
											'name' => 'language_name',
											'type' => 'text',
											'instructions' => 'Will be displayed as a tooltip for language flag',
											'column_width' => 25,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5396ed92c8295',
											'label' => 'Page',
											'name' => 'page',
											'type' => 'page_link',
											'column_width' => 50,
											'post_type' => array (
												0 => 'page',
												1 => 'event',
											),
											'allow_null' => 0,
											'multiple' => 0,
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'table',
									'button_label' => 'Add Language',
								),
							),
						),
						array (
							'label' => 'Content Box',
							'name' => 'content_box',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5396f7774d3c3',
									'label' => 'Content Box',
									'name' => 'content_box',
									'type' => 'wysiwyg',
									'column_width' => '',
									'default_value' => '',
									'toolbar' => 'full',
									'media_upload' => 'yes',
								),
							),
						),
						array (
							'label' => 'Contacts',
							'name' => 'contacts',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5396f7b64d3c5',
									'label' => 'Contacts List',
									'name' => 'contacts_list',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_5396f8e04d3c6',
											'label' => 'Role',
											'name' => 'role',
											'type' => 'text',
											'required' => 1,
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5396f8eb4d3c7',
											'label' => 'Name',
											'name' => 'name',
											'type' => 'text',
											'required' => 1,
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5396f90f4d3c8',
											'label' => 'Phone',
											'name' => 'phone',
											'type' => 'text',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_5396f9194d3c9',
											'label' => 'Email',
											'name' => 'email',
											'type' => 'email',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array (
											'key' => 'field_53ac1a26f2061',
											'label' => 'Address',
											'name' => 'address',
											'type' => 'textarea',
											'column_width' => 20,
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => 2,
											'formatting' => 'br',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'table',
									'button_label' => 'Add Contact',
								),
							),
						),
					),
					'button_label' => 'Add Widget',
					'min' => '',
					'max' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'default',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'event',
						'order_no' => 0,
						'group_no' => 1,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 2,
		));
		register_field_group(array (
			'id' => 'acf_page-attributes',
			'title' => 'Page Attributes',
			'fields' => array (
				array (
					'key' => 'field_53c1c4074a2f8',
					'label' => 'HTTPS',
					'name' => 'acf-https',
					'type' => 'true_false',
					'instructions' => 'Secure Post',
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_54b6b18685fc4',
					'label' => 'Shop Page',
					'name' => 'acf-shop_page',
					'type' => 'true_false',
					'instructions' => 'Check this field in order to	display shop header and full page width (without sidebar)',
					'message' => '',
					'default_value' => 0,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'event',
						'order_no' => 0,
						'group_no' => 1,
					),
				),
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'default',
						'order_no' => 0,
						'group_no' => 2,
					),
				),
			),
			'options' => array (
				'position' => 'side',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 3,
		));
		register_field_group(array (
			'id' => 'acf_featured-image',
			'title' => 'Featured Image',
			'fields' => array (
				array (
					'key' => 'field_539454cc7ac70',
					'label' => 'Featured Image',
					'name' => 'acf-featured_image',
					'type' => 'image',
					'instructions' => 'Image dimensions: 940x200px',
					'save_format' => 'object',
					'preview_size' => 'full',
					'library' => 'all',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'default',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-templates/shop-about.php',
						'order_no' => 0,
						'group_no' => 1,
					),
				),
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 0,
						'group_no' => 2,
					),
				),
			),
			'options' => array (
				'position' => 'side',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 4,
		));
		register_field_group(array (
			'id' => 'acf_event-attributes',
			'title' => 'Event Attributes',
			'fields' => array (
				array (
					'key' => 'field_533b07ca1cdbd',
					'label' => 'General',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53380bf11cedd',
					'label' => 'Start Date',
					'name' => 'acf-event_start_date',
					'type' => 'date_picker',
					'date_format' => 'yymmdd',
					'display_format' => 'dd/mm/yy',
					'first_day' => 0,
				),
				array (
					'key' => 'field_53380c601cede',
					'label' => 'End Date',
					'name' => 'acf-event_end_date',
					'type' => 'date_picker',
					'instructions' => 'For series of events, End Date must be equal or greater than the last event in the series',
					'required' => 1,
					'date_format' => 'yymmdd',
					'display_format' => 'dd/mm/yy',
					'first_day' => 0,
				),
				array (
					'key' => 'field_53380c8e1cedf',
					'label' => 'Description',
					'name' => 'acf-event_description',
					'type' => 'textarea',
					'instructions' => 'Maximum of 140 characters',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 140,
					'rows' => 2,
					'formatting' => 'br',
				),
				array (
					'key' => 'field_5404097f180a2',
					'label' => 'Landing Mode',
					'name' => 'acf-event_landing_mode',
					'type' => 'true_false',
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_53b55de7c5420',
					'label' => 'Payed Event',
					'name' => 'acf-event_payed_event',
					'type' => 'true_false',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_5404097f180a2',
								'operator' => '!=',
								'value' => '1',
							),
						),
						'allorany' => 'all',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_533b087a1cdc0',
					'label' => 'Images',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_533b083f1cdbf',
					'label' => 'Main Image',
					'name' => 'acf-event_main_image',
					'type' => 'image',
					'instructions' => 'The event\'s main image. Displayed in event\'s single page and in the Homepage banner.
		Image dimensions: 1140x527px',
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_533b08891cdc1',
					'label' => 'Slider Image',
					'name' => 'acf-event_slider_image',
					'type' => 'image',
					'instructions' => 'Displayed in Homepage events slider.
		Image dimensions: 380x380px',
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_533b09b41cdc2',
					'label' => 'Series of Events',
					'name' => '',
					'type' => 'tab',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_5404097f180a2',
								'operator' => '!=',
								'value' => '1',
							),
						),
						'allorany' => 'all',
					),
				),
				array (
					'key' => 'field_53af3c943fc6b',
					'label' => 'Series Price',
					'name' => 'acf-event_series_price',
					'type' => 'number',
					'instructions' => 'Numbers only without currency sign',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_53b55de7c5420',
								'operator' => '==',
								'value' => '1',
							),
						),
						'allorany' => 'all',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '₪',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array (
					'key' => 'field_53380d601cee2',
					'label' => 'Series of Events',
					'name' => 'acf-event_series_of_events',
					'type' => 'repeater',
					'instructions' => 'Events have to be sorted from earlier to last event',
					'sub_fields' => array (
						array (
							'key' => 'field_53380e971cee3',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'required' => 1,
							'column_width' => 20,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
						),
						array (
							'key' => 'field_53380eec1cee5',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'textarea',
							'column_width' => 30,
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
						array (
							'key' => 'field_53380ed11cee4',
							'label' => 'Date',
							'name' => 'date',
							'type' => 'date_picker',
							'required' => 1,
							'column_width' => 20,
							'date_format' => 'yymmdd',
							'display_format' => 'dd/mm/yy',
							'first_day' => 0,
						),
						array (
							'key' => 'field_53aadc67b6f9e',
							'label' => 'Price',
							'name' => 'price',
							'type' => 'number',
							'instructions' => 'Numbers only without currency sign',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_53b55de7c5420',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 10,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '₪',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array (
							'key' => 'field_53940bd94dca5',
							'label' => 'Ticket Net Link',
							'name' => 'ticket_net_link',
							'type' => 'text',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_53b55de7c5420',
										'operator' => '==',
										'value' => '1',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 20,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Event in Series',
				),
				array (
					'key' => 'field_533b07e11cdbe',
					'label' => 'External References',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53380ce21cee0',
					'label' => 'Homepage Banner Indicator',
					'name' => 'acf-event_homepage_banner_indicator',
					'type' => 'true_false',
					'message' => 'Publish on Homepage Banner?',
					'default_value' => 0,
				),
				array (
					'key' => 'field_534668b5c1266',
					'label' => 'Homepage Slider Indicator',
					'name' => 'acf-event_homepage_slider_indicator',
					'type' => 'true_false',
					'message' => 'Publish on Homepage Events Slider?',
					'default_value' => 1,
				),
				array (
					'key' => 'field_53380d371cee1',
					'label' => 'Ticket Net Link',
					'name' => 'acf-event_ticket_net_link',
					'type' => 'text',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_53b55de7c5420',
								'operator' => '==',
								'value' => '1',
							),
						),
						'allorany' => 'all',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_533b09ef1cdc3',
					'label' => 'Registration Form',
					'name' => 'acf-event_registration_form',
					'type' => 'true_false',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_5404097f180a2',
								'operator' => '!=',
								'value' => '1',
							),
							array (
								'field' => 'field_53b55de7c5420',
								'operator' => '!=',
								'value' => '1',
							),
						),
						'allorany' => 'all',
					),
					'message' => 'Include in Registration Form?',
					'default_value' => 0,
				),
				array (
					'key' => 'field_540409c2180a3',
					'label' => 'Landing Mode',
					'name' => '',
					'type' => 'tab',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_5404097f180a2',
								'operator' => '==',
								'value' => '1',
							),
						),
						'allorany' => 'all',
					),
				),
				array (
					'key' => 'field_540409e8180a4',
					'label' => 'Background Image',
					'name' => 'acf-event_background_image',
					'type' => 'image',
					'instructions' => 'Image Width (px): 940',
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'event',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 5,
		));
		register_field_group(array (
			'id' => 'acf_event-category-attributes',
			'title' => 'Event Category Attributes',
			'fields' => array (
				array (
					'key' => 'field_534a4d24617b3',
					'label' => 'Singular Name',
					'name' => 'acf-event_category_singular_name',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_534aad1f04025',
					'label' => 'Next Event in Series Title',
					'name' => 'acf-event_category_next_event',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'ef_taxonomy',
						'operator' => '==',
						'value' => 'event_category',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 6,
		));
		register_field_group(array (
			'id' => 'acf_contact-details-options',
			'title' => 'Contact Details Options',
			'fields' => array (
				array (
					'key' => 'field_53567d4044fc6',
					'label' => 'Contact Details',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53564d254e01f',
					'label' => 'Contact Details',
					'name' => 'acf-options_contact_details',
					'type' => 'flexible_content',
					'layouts' => array (
						array (
							'label' => 'Text Box',
							'name' => 'text_box',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_53566b52033cb',
									'label' => 'Type',
									'name' => 'type',
									'type' => 'select',
									'column_width' => '',
									'choices' => array (
										'main' => 'Main Text Box',
										'sub' => 'Sub Text Box',
									),
									'default_value' => 'sub',
									'allow_null' => 0,
									'multiple' => 0,
								),
								array (
									'key' => 'field_53564d8a4e020',
									'label' => 'Title (en)',
									'name' => 'title_en',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5382f733c6344',
									'label' => 'Title (he)',
									'name' => 'title_he',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
								),
								array (
									'key' => 'field_53564d9c4e021',
									'label' => 'Content (en)',
									'name' => 'content_en',
									'type' => 'wysiwyg',
									'column_width' => '',
									'default_value' => '',
									'toolbar' => 'full',
									'media_upload' => 'no',
								),
								array (
									'key' => 'field_5382f98dbb4d7',
									'label' => 'Content (he)',
									'name' => 'content_he',
									'type' => 'wysiwyg',
									'column_width' => '',
									'default_value' => '',
									'toolbar' => 'full',
									'media_upload' => 'no',
								),
								array (
									'key' => 'field_5368819f56c6a',
									'label' => 'Small Resolution New Column',
									'name' => 'sm_new_col',
									'type' => 'true_false',
									'conditional_logic' => array (
										'status' => 1,
										'rules' => array (
											array (
												'field' => 'field_53566b52033cb',
												'operator' => '==',
												'value' => 'sub',
											),
										),
										'allorany' => 'all',
									),
									'column_width' => '',
									'message' => 'Open a New Column in Small Resolution?',
									'default_value' => 0,
								),
								array (
									'key' => 'field_536883cb56c6b',
									'label' => 'Small Resolution Cell Height',
									'name' => 'sm_cell_height',
									'type' => 'number',
									'conditional_logic' => array (
										'status' => 1,
										'rules' => array (
											array (
												'field' => 'field_53566b52033cb',
												'operator' => '==',
												'value' => 'sub',
											),
										),
										'allorany' => 'all',
									),
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => 'px',
									'min' => '',
									'max' => '',
									'step' => '',
								),
							),
						),
						array (
							'label' => 'Map',
							'name' => 'map',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_53566af3033ca',
									'label' => 'Map Image',
									'name' => 'map_image',
									'type' => 'image',
									'instructions' => 'Image dimensions: 720x120px',
									'column_width' => '',
									'save_format' => 'object',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
								array (
									'key' => 'field_53567194033cc',
									'label' => 'Google Maps Link',
									'name' => 'google_maps_link',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => 'http://',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_5368854d65237',
									'label' => 'Small Resolution New Column',
									'name' => 'sm_new_col',
									'type' => 'true_false',
									'column_width' => '',
									'message' => 'Open a New Column in Small Resolution?',
									'default_value' => 0,
								),
							),
						),
						array (
							'label' => 'Single Link',
							'name' => 'single_link',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_535671de033ce',
									'label' => 'Icon',
									'name' => 'icon',
									'type' => 'image',
									'instructions' => 'Image dimensions: 40x40px',
									'column_width' => '',
									'save_format' => 'object',
									'preview_size' => 'thumbnail',
									'library' => 'all',
								),
								array (
									'key' => 'field_53567207033cf',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => 'http://',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
								array (
									'key' => 'field_53567232033d0',
									'label' => 'Text (en)',
									'name' => 'text_en',
									'type' => 'textarea',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'formatting' => 'br',
								),
								array (
									'key' => 'field_538352d9195f8',
									'label' => 'Text (he)',
									'name' => 'text_he',
									'type' => 'textarea',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'formatting' => 'br',
								),
								array (
									'key' => 'field_5356796c888a9',
									'label' => 'Show only in Mobile',
									'name' => 'show_in_mobile',
									'type' => 'true_false',
									'column_width' => '',
									'message' => '',
									'default_value' => 0,
								),
								array (
									'key' => 'field_5368857f65238',
									'label' => 'Small Resolution New Column',
									'name' => 'sm_new_col',
									'type' => 'true_false',
									'column_width' => '',
									'message' => 'Open a New Column in Small Resolution?',
									'default_value' => 0,
								),
							),
						),
						array (
							'label' => 'Multiple Links',
							'name' => 'multiple_links',
							'display' => 'row',
							'min' => '',
							'max' => '',
							'sub_fields' => array (
								array (
									'key' => 'field_5356728b033d2',
									'label' => 'Links',
									'name' => 'links',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_535672ba033d3',
											'label' => 'Icon',
											'name' => 'icon',
											'type' => 'text',
											'instructions' => '"Font Awesome" icon class name',
											'column_width' => 15,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
										array (
											'key' => 'field_535672d7033d4',
											'label' => 'Link (en)',
											'name' => 'link_en',
											'type' => 'text',
											'column_width' => 30,
											'default_value' => '',
											'placeholder' => 'http://',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_53c63339506fb',
											'label' => 'Link (he)',
											'name' => 'link_he',
											'type' => 'text',
											'column_width' => 30,
											'default_value' => '',
											'placeholder' => 'http://',
											'prepend' => '',
											'append' => '',
											'formatting' => 'html',
											'maxlength' => '',
										),
										array (
											'key' => 'field_53593b7dde807',
											'label' => 'Color',
											'name' => 'color',
											'type' => 'color_picker',
											'column_width' => 25,
											'default_value' => '#000000',
										),
									),
									'row_min' => '',
									'row_limit' => '',
									'layout' => 'table',
									'button_label' => 'Add Link',
								),
								array (
									'key' => 'field_536885e46523a',
									'label' => 'Small Resolution New Column',
									'name' => 'sm_new_col',
									'type' => 'true_false',
									'column_width' => '',
									'message' => 'Open a New Column in Small Resolution?',
									'default_value' => 0,
								),
								array (
									'key' => 'field_536886046523b',
									'label' => 'Small Resolution Cell Height',
									'name' => 'sm_cell_height',
									'type' => 'number',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => 'px',
									'min' => '',
									'max' => '',
									'step' => '',
								),
							),
						),
						array (
							'label' => 'Opening Hours Message',
							'name' => 'opening_hours_message',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_535682fab4d1e',
									'label' => 'Hide',
									'name' => 'hide',
									'type' => 'true_false',
									'column_width' => '',
									'message' => 'Hide messages temporarily',
									'default_value' => 0,
								),
								array (
									'key' => 'field_5368863e6523c',
									'label' => 'Small Resolution New Column',
									'name' => 'sm_new_col',
									'type' => 'true_false',
									'column_width' => '',
									'message' => 'Open a New Column in Small Resolution?',
									'default_value' => 0,
								),
								array (
									'key' => 'field_536886576523d',
									'label' => 'Small Resolution Cell Height',
									'name' => 'sm_cell_height',
									'type' => 'number',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => 'px',
									'min' => '',
									'max' => '',
									'step' => '',
								),
							),
						),
					),
					'button_label' => 'Add Contact Detail',
					'min' => '',
					'max' => '',
				),
				array (
					'key' => 'field_53567d5044fc7',
					'label' => 'Opening Hours',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53567d6544fc8',
					'label' => 'Opening Hours',
					'name' => 'acf-options_opening_hours',
					'type' => 'repeater',
					'instructions' => 'Define all week days from Sunday to Friday in ascending order',
					'sub_fields' => array (
						array (
							'key' => 'field_53567e3b44fc9',
							'label' => 'Day',
							'name' => 'day',
							'type' => 'select',
							'column_width' => 34,
							'choices' => array (
								0 => 'Sunday',
								1 => 'Monday',
								2 => 'Tuesday',
								3 => 'Wednesday',
								4 => 'Thursday',
								5 => 'Friday',
							),
							'default_value' => '',
							'allow_null' => 0,
							'multiple' => 0,
						),
						array (
							'key' => 'field_53567f0f44fca',
							'label' => 'Open',
							'name' => 'open',
							'type' => 'select',
							'column_width' => 33,
							'choices' => array (
								'0800' => '08:00',
								'0830' => '08:30',
								'0900' => '09:00',
								'0930' => '09:30',
								1000 => '10:00',
								1030 => '10:30',
								1100 => '11:00',
								1130 => '11:30',
								1200 => '12:00',
								1230 => '12:30',
								1300 => '13:00',
								1330 => '13:30',
								1400 => '14:00',
								1430 => '14:30',
								1500 => '15:00',
								1530 => '15:30',
								1600 => '16:00',
								1630 => '16:30',
								1700 => '17:00',
								1730 => '17:30',
								1800 => '18:00',
								1830 => '18:30',
								1900 => '19:00',
								1930 => '19:30',
								2000 => '20:00',
								2030 => '20:30',
								2100 => '21:00',
								2130 => '21:30',
								2200 => '22:00',
								2230 => '22:30',
								2300 => '23:00',
							),
							'default_value' => 900,
							'allow_null' => 0,
							'multiple' => 0,
						),
						array (
							'key' => 'field_53567f7f44fcb',
							'label' => 'Close',
							'name' => 'close',
							'type' => 'select',
							'column_width' => 33,
							'choices' => array (
								'0800' => '08:00',
								'0830' => '08:30',
								'0900' => '09:00',
								'0930' => '09:30',
								1000 => '10:00',
								1030 => '10:30',
								1100 => '11:00',
								1130 => '11:30',
								1200 => '12:00',
								1230 => '12:30',
								1300 => '13:00',
								1330 => '13:30',
								1400 => '14:00',
								1430 => '14:30',
								1500 => '15:00',
								1530 => '15:30',
								1600 => '16:00',
								1630 => '16:30',
								1700 => '17:00',
								1730 => '17:30',
								1800 => '18:00',
								1830 => '18:30',
								1900 => '19:00',
								1930 => '19:30',
								2000 => '20:00',
								2030 => '20:30',
								2100 => '21:00',
								2130 => '21:30',
								2200 => '22:00',
								2230 => '22:30',
								2300 => '23:00',
							),
							'default_value' => 1700,
							'allow_null' => 0,
							'multiple' => 0,
						),
					),
					'row_min' => 6,
					'row_limit' => 6,
					'layout' => 'table',
					'button_label' => 'Add Day',
				),
				array (
					'key' => 'field_5356837edc4fc',
					'label' => 'Open Message (en)',
					'name' => 'acf-options_open_message_en',
					'type' => 'text',
					'instructions' => 'Use "%s" string as a placeholder for Closing Hour',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385bb18b17c2',
					'label' => 'Open Message (he)',
					'name' => 'acf-options_open_message_he',
					'type' => 'text',
					'instructions' => 'Use "%s" string as a placeholder for Closing Hour',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5356842fdc4fd',
					'label' => 'Close Message (en)',
					'name' => 'acf-options_close_message_en',
					'type' => 'text',
					'instructions' => 'Use "%s" strings as placeholders for next Day and Opening Hour (in that order)',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385bb4cb17c3',
					'label' => 'Close Message (he)',
					'name' => 'acf-options_close_message_he',
					'type' => 'text',
					'instructions' => 'Use "%s" strings as placeholders for next Day and Opening Hour (in that order)',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_535df4360d0fe',
					'label' => 'Opening Today Message (en)',
					'name' => 'acf-options_opening_today_message_en',
					'type' => 'text',
					'instructions' => 'Use "%s" string as a placeholder for today\'s Opening Hour',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385bbb1b17c4',
					'label' => 'Opening Today Message (he)',
					'name' => 'acf-options_opening_today_message_he',
					'type' => 'text',
					'instructions' => 'Use "%s" string as a placeholder for today\'s Opening Hour',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385d19f441c1',
					'label' => '"tomorrow" String (en)',
					'name' => 'acf-options_tomorrow_str_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385d230441c2',
					'label' => '"tomorrow" String (he)',
					'name' => 'acf-options_tomorrow_str_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385d252441c3',
					'label' => '"on day" String (en)',
					'name' => 'acf-options_on_day_str_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385d2df441c4',
					'label' => '"on day" String (he)',
					'name' => 'acf-options_on_day_str_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-contact-details',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 7,
		));
		register_field_group(array (
			'id' => 'acf_product-category-attributes',
			'title' => 'Product Category Attributes',
			'fields' => array (
				array (
					'key' => 'field_549fc9e8ba260',
					'label' => 'Banner Title',
					'name' => 'acf-product-category-banner_title',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_549fdda494064',
					'label' => 'Banner Text',
					'name' => 'acf-product-category-banner_text',
					'type' => 'wysiwyg',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'no',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'ef_taxonomy',
						'operator' => '==',
						'value' => 'product_cat',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
				array (
					array (
						'param' => 'ef_taxonomy',
						'operator' => '==',
						'value' => 'occasion',
						'order_no' => 0,
						'group_no' => 1,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 7,
		));
		register_field_group(array (
			'id' => 'acf_general-options',
			'title' => 'General Options',
			'fields' => array (
				array (
					'key' => 'field_53564aea2839b',
					'label' => 'Strings',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53564a5428399',
					'label' => 'Event End Date Prepend (en)',
					'name' => 'acf-options_event_end_date_prepend_en',
					'type' => 'text',
					'instructions' => 'e.g. "Till" for event ends by January 1st will be referenced as: "Till Jan 01"',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385d4d0cbb39',
					'label' => 'Event End Date Prepend (he)',
					'name' => 'acf-options_event_end_date_prepend_he',
					'type' => 'text',
					'instructions' => 'e.g. "Till" for event ends by January 1st will be referenced as: "Till Jan 01"',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53564aae2839a',
					'label' => 'Series of Events Prepend (en)',
					'name' => 'acf-options_series_of_events_prepend_en',
					'type' => 'text',
					'instructions' => 'e.g. "Series of" for "Lectures" events will be referenced as: "Series of Lectures"',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385d4f5cbb3a',
					'label' => 'Series of Events Prepend (he)',
					'name' => 'acf-options_series_of_events_prepend_he',
					'type' => 'text',
					'instructions' => 'e.g. "Series of" for "Lectures" events will be referenced as: "Series of Lectures"',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5385f44231084',
					'label' => 'Event\'s Month Prepend (he)',
					'name' => 'acf-options_event_month_prepend_he',
					'type' => 'text',
					'instructions' => 'לדוגמא: המחרוזת "ב" תציג את התאריך 10.1 כ- "10 בינואר"',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_539efcaefc032',
					'label' => 'Future Events List Title (en)',
					'name' => 'acf-options_future_events_list_title_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_539efef9fc033',
					'label' => 'Future Events List Title (he)',
					'name' => 'acf-options_future_events_list_title_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b522849070b',
					'label' => 'Event Buttons',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53b522999070c',
					'label' => 'Order Tickets (en)',
					'name' => 'acf-options_event_btn_order_tickets_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b5235d9070d',
					'label' => 'Order Tickets (he)',
					'name' => 'acf-options_event_btn_order_tickets_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b5237a9070e',
					'label' => 'Purchase Series (en)',
					'name' => 'acf-options_event_btn_purchase_series_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b523b99070f',
					'label' => 'Purchase Series (he)',
					'name' => 'acf-options_event_btn_purchase_series_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b523f090710',
					'label' => 'Reservation (en)',
					'name' => 'acf-options_event_btn_reservation_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b5242390711',
					'label' => 'Reservation (he)',
					'name' => 'acf-options_event_btn_reservation_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b595827e509',
					'label' => 'Reservation Form Page',
					'name' => 'acf-options_events_reservation_form_page',
					'type' => 'post_object',
					'instructions' => 'This field can be specified for only one language, the rest of the languages ??will be updated automatically',
					'required' => 1,
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_53b52488d3bdd',
					'label' => 'Free Admittance (en)',
					'name' => 'acf-options_event_btn_free_admittance_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b524b0d3bde',
					'label' => 'Free Admittance (he)',
					'name' => 'acf-options_event_btn_free_admittance_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b524e6d3bdf',
					'label' => 'Read More (en)',
					'name' => 'acf-options_event_btn_read_more_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53b5250ad3be0',
					'label' => 'Read More (he)',
					'name' => 'acf-options_event_btn_read_more_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_53aff4c3c5ee0',
					'label' => 'Services Costs',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53aff50dc5ee1',
					'label' => 'Services Costs',
					'name' => 'acf-options_services_costs',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_53aff525c5ee2',
							'label' => 'Service ID',
							'name' => 'service_id',
							'type' => 'text',
							'instructions' => 'Form ID',
							'required' => 1,
							'column_width' => 50,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_53aff56ac5ee3',
							'label' => 'Cost',
							'name' => 'cost',
							'type' => 'number',
							'instructions' => 'Numbers only without currency sign',
							'required' => 1,
							'column_width' => 50,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '₪',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Service',
				),
				array (
					'key' => 'field_53b39fb2566d4',
					'label' => '404 Page',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53b17ba0dc73f',
					'label' => '404 Top Message (en)',
					'name' => 'acf-options_404_top_message_en',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_53b180a2dc740',
					'label' => '404 Top Message (he)',
					'name' => 'acf-options_404_top_message_he',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_53b39ebe96f07',
					'label' => '404 Bottom Message (en)',
					'name' => 'acf-options_404_bottom_message_en',
					'type' => 'wysiwyg',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'no',
				),
				array (
					'key' => 'field_53b39f0b568c4',
					'label' => '404 Bottom Message (he)',
					'name' => 'acf-options_404_bottom_message_he',
					'type' => 'wysiwyg',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'no',
				),
				array (
					'key' => 'field_53b39fc7566d5',
					'label' => 'Misc',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_53b03b1ebef28',
					'label' => 'Events Page',
					'name' => 'acf-options_events_page',
					'type' => 'post_object',
					'instructions' => 'Used to display relevant event categories in the website menus. This field can be specified for only one language, the rest of the languages ??will be updated automatically',
					'required' => 1,
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_53da4777d159f',
					'label' => 'Blog Page',
					'name' => 'acf-options_blog_page',
					'type' => 'post_object',
					'instructions' => 'Used to display Blog link in Blog\'s archive page. This field can be specified for only one language, the rest of the languages ??will be updated automatically',
					'required' => 1,
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_53e0e8376d77e',
					'label' => 'Event Categories to include in Past Events page',
					'name' => 'acf-options_event_categories',
					'type' => 'taxonomy',
					'required' => 1,
					'taxonomy' => 'event_category',
					'field_type' => 'checkbox',
					'allow_null' => 0,
					'load_save_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
				),
				array (
					'key' => 'field_53bbe9e2f765c',
					'label' => 'Form Footer (en)',
					'name' => 'acf-options_form_footer_en',
					'type' => 'wysiwyg',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'yes',
				),
				array (
					'key' => 'field_53bbea2af765d',
					'label' => 'Form Footer (he)',
					'name' => 'acf-options_form_footer_he',
					'type' => 'wysiwyg',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'yes',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-general',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 8,
		));
		register_field_group(array (
			'id' => 'acf_product-badge-attributes',
			'title' => 'Product Badge Attributes',
			'fields' => array (
				array (
					'key' => 'field_548ca7e03b90e',
					'label' => 'Badge Image',
					'name' => 'acf-product-badge_image',
					'type' => 'image',
					'required' => 1,
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'ef_taxonomy',
						'operator' => '==',
						'value' => 'badge',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 8,
		));
		register_field_group(array (
			'id' => 'acf_shop-about',
			'title' => 'Shop - About',
			'fields' => array (
				array (
					'key' => 'field_551d2938892a0',
					'label' => 'Team Pre Text',
					'name' => 'acf-shop_about_team_pre_text',
					'type' => 'wysiwyg',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'no',
				),
				array (
					'key' => 'field_551d179f7531a',
					'label' => 'Team Members',
					'name' => 'acf-shop_about_team_members',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_551d1d54d76f4',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'required' => 1,
							'column_width' => 30,
							'save_format' => 'object',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_551d1d2cd76f3',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'required' => 1,
							'column_width' => 20,
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
						),
						array (
							'key' => 'field_551d1d70d76f5',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'textarea',
							'column_width' => 50,
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Team Member',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-templates/shop-about.php',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 9,
		));
		register_field_group(array (
			'id' => 'acf_shop-why-shop-with-us',
			'title' => 'Shop - Why Shop With Us',
			'fields' => array (
				array (
					'key' => 'field_55192487997b9',
					'label' => 'Shop WSWU Template Layouts',
					'name' => 'acf-shop_wswu_template_layouts',
					'type' => 'flexible_content',
					'layouts' => array (
						array (
							'label' => 'Banners',
							'name' => 'banners',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_551925ba7a0d4',
									'label' => 'banners',
									'name' => 'banners',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_551926747a0d6',
											'label' => 'Image Size',
											'name' => 'image_size',
											'type' => 'select',
											'column_width' => 20,
											'choices' => array (
												'small' => 'Small (424x220px)',
												'big' => 'Big (704x220px )',
											),
											'default_value' => '',
											'allow_null' => 0,
											'multiple' => 0,
										),
										array (
											'key' => 'field_551925f67a0d5',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'column_width' => 30,
											'save_format' => 'object',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_551929dc7a0d7',
											'label' => 'Text',
											'name' => 'text',
											'type' => 'text',
											'column_width' => 50,
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'formatting' => 'none',
											'maxlength' => '',
										),
									),
									'row_min' => '',
									'row_limit' => 6,
									'layout' => 'table',
									'button_label' => 'Add Image',
								),
							),
						),
						array (
							'label' => 'Content',
							'name' => 'content',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_533d36598e076',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'none',
									'maxlength' => '',
								),
								array (
									'key' => 'field_533d368b8e077',
									'label' => 'Columns',
									'name' => 'columns',
									'type' => 'repeater',
									'column_width' => '',
									'sub_fields' => array (
										array (
											'key' => 'field_55192b127a0d8',
											'label' => 'Icon',
											'name' => 'icon',
											'type' => 'image',
											'instructions' => 'Image dimensions: 65x65px',
											'column_width' => 35,
											'save_format' => 'object',
											'preview_size' => 'thumbnail',
											'library' => 'all',
										),
										array (
											'key' => 'field_55192c6a6d5ad',
											'label' => 'Content',
											'name' => 'content',
											'type' => 'wysiwyg',
											'column_width' => 65,
											'default_value' => '',
											'toolbar' => 'full',
											'media_upload' => 'no',
										),
									),
									'row_min' => '',
									'row_limit' => 3,
									'layout' => 'table',
									'button_label' => 'Add Column',
								),
							),
						),
						array (
							'label' => 'Video',
							'name' => 'video',
							'display' => 'row',
							'min' => 0,
							'max' => 1,
							'sub_fields' => array (
								array (
									'key' => 'field_533d374f8e079',
									'label' => 'Video Link',
									'name' => 'video_link',
									'type' => 'text',
									'instructions' => 'Full embedded link',
									'column_width' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'formatting' => 'html',
									'maxlength' => '',
								),
							),
						),
					),
					'button_label' => 'Add Layout',
					'min' => '',
					'max' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-templates/shop-why-shop-with-us.php',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
					0 => 'the_content',
				),
			),
			'menu_order' => 10,
		));
		register_field_group(array (
			'id' => 'acf_shop-options',
			'title' => 'Shop Options',
			'fields' => array (
				array (
					'key' => 'field_54ad4405241f8',
					'label' => 'Homepage Banners',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_54b23b3e25fe3',
					'label' => 'Banners',
					'name' => 'acf-options-shop_banners',
					'type' => 'repeater',
					'instructions' => '<p>Image dimensions:</p>
		
		<div>Image #01: 704x360px</div>
		<div>Image #02: 424x360px</div>
		<div>Image #03: 424x360px</div>
		<div>Image #04: 704x360px</div>',
					'sub_fields' => array (
						array (
							'key' => 'field_54b23b8825fe4',
							'label' => 'Image (en)',
							'name' => 'image_en',
							'type' => 'image',
							'column_width' => 25,
							'save_format' => 'object',
							'preview_size' => 'full',
							'library' => 'all',
						),
						array (
							'key' => 'field_54b25627788dd',
							'label' => 'Image (he)',
							'name' => 'image_he',
							'type' => 'image',
							'column_width' => 25,
							'save_format' => 'object',
							'preview_size' => 'full',
							'library' => 'all',
						),
						array (
							'key' => 'field_54b24a03f0b2c',
							'label' => 'Link Type (en)',
							'name' => 'link_type_en',
							'type' => 'select',
							'required' => 1,
							'column_width' => 25,
							'choices' => array (
								'no' => 'No Link',
								'page' => 'Page/Product',
								'category' => 'Product Category',
								'occasion' => 'Occasion',
								'artist' => 'Artist',
								'ext' => 'External Link',
							),
							'default_value' => 'no',
							'allow_null' => 0,
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b256a3788de',
							'label' => 'Link Type (he)',
							'name' => 'link_type_he',
							'type' => 'select',
							'required' => 1,
							'column_width' => 25,
							'choices' => array (
								'no' => 'No Link',
								'page' => 'Page/Product',
								'category' => 'Product Category',
								'occasion' => 'Occasion',
								'artist' => 'Artist',
								'ext' => 'External Link',
							),
							'default_value' => 'no',
							'allow_null' => 0,
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b23bc825fe5',
							'label' => 'Page/Product Link (en)',
							'name' => 'page_product_link_en',
							'type' => 'post_object',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b24a03f0b2c',
										'operator' => '==',
										'value' => 'page',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'post_type' => array (
								0 => 'page',
								1 => 'product',
							),
							'taxonomy' => array (
								0 => 'all',
							),
							'allow_null' => 1,
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b2598e788e3',
							'label' => 'Page/Product Link (he)',
							'name' => 'page_product_link_he',
							'type' => 'post_object',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b256a3788de',
										'operator' => '==',
										'value' => 'page',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'post_type' => array (
								0 => 'page',
								1 => 'product',
							),
							'taxonomy' => array (
								0 => 'all',
							),
							'allow_null' => 1,
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b23e37f0b29',
							'label' => 'Product Category Link (en)',
							'name' => 'product_category_link_en',
							'type' => 'taxonomy',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b24a03f0b2c',
										'operator' => '==',
										'value' => 'category',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'taxonomy' => 'product_cat',
							'field_type' => 'select',
							'allow_null' => 1,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b25979788e2',
							'label' => 'Product Category Link (he)',
							'name' => 'product_category_link_he',
							'type' => 'taxonomy',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b256a3788de',
										'operator' => '==',
										'value' => 'category',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'taxonomy' => 'product_cat',
							'field_type' => 'select',
							'allow_null' => 1,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b23f56f0b2a',
							'label' => 'Product Occasion Link (en)',
							'name' => 'product_occasion_link_en',
							'type' => 'taxonomy',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b24a03f0b2c',
										'operator' => '==',
										'value' => 'occasion',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'taxonomy' => 'occasion',
							'field_type' => 'select',
							'allow_null' => 1,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b25961788e1',
							'label' => 'Product Occasion Link (he)',
							'name' => 'product_occasion_link_he',
							'type' => 'taxonomy',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b256a3788de',
										'operator' => '==',
										'value' => 'occasion',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'taxonomy' => 'occasion',
							'field_type' => 'select',
							'allow_null' => 1,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b23f7bf0b2b',
							'label' => 'Product Artist Link (en)',
							'name' => 'product_artist_link_en',
							'type' => 'taxonomy',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b24a03f0b2c',
										'operator' => '==',
										'value' => 'artist',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'taxonomy' => 'artist',
							'field_type' => 'select',
							'allow_null' => 1,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b25751788e0',
							'label' => 'Product Artist Link (he)',
							'name' => 'product_artist_link_he',
							'type' => 'taxonomy',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b256a3788de',
										'operator' => '==',
										'value' => 'artist',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'taxonomy' => 'artist',
							'field_type' => 'select',
							'allow_null' => 1,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54b23c6b25fe6',
							'label' => 'External Link (en)',
							'name' => 'external_link_en',
							'type' => 'text',
							'instructions' => 'Will be opened in a new tab',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b24a03f0b2c',
										'operator' => '==',
										'value' => 'ext',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_54b2570e788df',
							'label' => 'External Link (he)',
							'name' => 'external_link_he',
							'type' => 'text',
							'instructions' => 'Will be opened in a new tab',
							'conditional_logic' => array (
								'status' => 1,
								'rules' => array (
									array (
										'field' => 'field_54b256a3788de',
										'operator' => '==',
										'value' => 'ext',
									),
								),
								'allorany' => 'all',
							),
							'column_width' => 25,
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => 4,
					'row_limit' => 4,
					'layout' => 'row',
					'button_label' => 'Add Banner',
				),
				array (
					'key' => 'field_54ae437133895',
					'label' => 'Homepage Sliders',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_54ae444447ed3',
					'label' => 'Sliders',
					'name' => 'acf-options-shop_sliders',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_54ae44a847ed4',
							'label' => 'Title (en)',
							'name' => 'title_en',
							'type' => 'wysiwyg',
							'instructions' => 'You may declare Category/Occasion name as link',
							'column_width' => '',
							'default_value' => '',
							'toolbar' => 'basic',
							'media_upload' => 'no',
						),
						array (
							'key' => 'field_54ae49ac06d6a',
							'label' => 'Title (he)',
							'name' => 'title_he',
							'type' => 'wysiwyg',
							'instructions' => 'You may declare Category/Occasion name as link',
							'column_width' => '',
							'default_value' => '',
							'toolbar' => 'basic',
							'media_upload' => 'no',
						),
						array (
							'key' => 'field_54ae451047ed5',
							'label' => 'Products',
							'name' => 'products',
							'type' => 'relationship',
							'instructions' => 'This field can be specified for only one language, the rest of the languages will be updated automatically',
							'column_width' => '',
							'return_format' => 'object',
							'post_type' => array (
								0 => 'product',
							),
							'taxonomy' => array (
								0 => 'all',
							),
							'filters' => array (
								0 => 'search',
							),
							'result_elements' => array (
								0 => 'featured_image',
								1 => 'post_title',
							),
							'max' => '',
						),
					),
					'row_min' => '',
					'row_limit' => 4,
					'layout' => 'row',
					'button_label' => 'Add Slider',
				),
				array (
					'key' => 'field_548d4f4a0945d',
					'label' => 'Experience',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_548d4f650945e',
					'label' => 'Banner (en)',
					'name' => 'acf-options_experience_banner_en',
					'type' => 'image',
					'instructions' => 'Image dimensions: 1170x184px',
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_551bf2f6847bc',
					'label' => 'Banner (he)',
					'name' => 'acf-options_experience_banner_he',
					'type' => 'image',
					'instructions' => 'Image dimensions: 1170x184px',
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_551bfb72256c3',
					'label' => 'Experience Page',
					'name' => 'acf-options_experience_page',
					'type' => 'post_object',
					'instructions' => 'This field can be specified for only one language, the rest of the languages will be updated automatically',
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_5533a5d3f26dd',
					'label' => 'Emails',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_5533a61404e06',
					'label' => 'Customer Processing Order Title',
					'name' => 'acf-email_customer_processing_order_title',
					'type' => 'image',
					'instructions' => 'Image dimensions: 600x100px',
					'save_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_5533f7277cc2a',
					'label' => 'Customer Completed Order Title',
					'name' => 'acf-email_customer_completed_order_title',
					'type' => 'image',
					'instructions' => 'Image dimensions: 600x100px',
					'save_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_54802bbb41ddd',
					'label' => 'Footer',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_54802cfe41dde',
					'label' => 'Returns Policy Title (en)',
					'name' => 'acf-options_returns_policy_title_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54802d3e41ddf',
					'label' => 'Returns Policy Text (en)',
					'name' => 'acf-options_returns_policy_text_en',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_54802d6441de0',
					'label' => 'Returns Policy Title (he)',
					'name' => 'acf-options_returns_policy_title_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54802d8241de1',
					'label' => 'Returns Policy Text (he)',
					'name' => 'acf-options_returns_policy_text_he',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_54802d9d41de2',
					'label' => 'Returns Policy Page',
					'name' => 'acf-options_returns_policy_Page',
					'type' => 'post_object',
					'instructions' => 'This field can be specified for only one language, the rest of the languages will be updated automatically',
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_54802e0341de3',
					'label' => 'Shipment Policy Title (en)',
					'name' => 'acf-options_shipment_policy_title_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54802e3141de4',
					'label' => 'Shipment Policy Text (en)',
					'name' => 'acf-options_shipment_policy_text_en',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_54802e4741de5',
					'label' => 'Shipment Policy Title (he)',
					'name' => 'acf-options_shipment_policy_title_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54802e5b41de6',
					'label' => 'Shipment Policy Text (he)',
					'name' => 'acf-options_shipment_policy_text_he',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_54802e7341de7',
					'label' => 'Shipment Policy Page',
					'name' => 'acf-options_shipment_policy_page',
					'type' => 'post_object',
					'instructions' => 'This field can be specified for only one language, the rest of the languages will be updated automatically',
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_54802eaa41de8',
					'label' => 'FAQs Title (en)',
					'name' => 'acf-options_faqs_title_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54802ec141de9',
					'label' => 'FAQs Text (en)',
					'name' => 'acf-options_faqs_text_en',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_54802f0841dea',
					'label' => 'FAQs Title (he)',
					'name' => 'acf-options_faqs_title_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_54802f1f41deb',
					'label' => 'FAQs Text (he)',
					'name' => 'acf-options_faqs_text_he',
					'type' => 'textarea',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'formatting' => 'br',
				),
				array (
					'key' => 'field_54802f4241dec',
					'label' => 'FAQs Page',
					'name' => 'acf-options_faqs_page',
					'type' => 'post_object',
					'instructions' => 'This field can be specified for only one language, the rest of the languages will be updated automatically',
					'post_type' => array (
						0 => 'page',
					),
					'taxonomy' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_553667710b0f6',
					'label' => 'Misc',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_5536677b0b0f7',
					'label' => 'Product Image Disclaimer (en)',
					'name' => 'acf-options_product_image_disclaimer_en',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5536679f0b0f8',
					'label' => 'Product Image Disclaimer (he)',
					'name' => 'acf-options_product_image_disclaimer_he',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'none',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-shop',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'default',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 13,
		));
	}
	*/
	
	/**
	 * Add custom admin columns
	 */

	// add columns to post subpannel
	function event_subpannel_columns($columns) {
		$event_columns = array(
			'start_date'	=> 'Start Date',
			'end_date'		=> 'End Date',
			'banner_ind'	=> 'Homepage Banner',
			'slider_ind'	=> 'Homepage Slider'
		);
		$columns = array_merge(
			array_slice($columns, 0, -1),	// before
			$event_columns,					// inserted
			array_slice($columns, -1)		// after
		);
	
		return $columns;
	}
	add_filter('manage_event_posts_columns', 'event_subpannel_columns');
	
	// add columns values to post subpannel
	function event_subpannel_columns_values($columns, $post_id) {
		global $post;
		
		if ($columns == 'start_date') {
			$start_date = get_field('acf-event_start_date', $post->ID);
			echo ($start_date) ? date( 'd/m/Y', strtotime($start_date) ) : '';
		}
		else if ($columns == 'end_date') {
			$end_date = get_field('acf-event_end_date', $post->ID);
			echo ($end_date) ? date( 'd/m/Y', strtotime($end_date) ) : '';
		}
		else if ($columns == 'banner_ind') {
			$banner_ind = get_field('acf-event_homepage_banner_indicator', $post->ID);
			echo ($banner_ind) ? 'Show' : '';
		}
		else if ($columns == 'slider_ind') {
			$slider_ind = get_field('acf-event_homepage_slider_indicator', $post->ID);
			echo ($slider_ind) ? 'Show' : '';
		}
	}
	add_action('manage_event_posts_custom_column', 'event_subpannel_columns_values', 10, 2);
	
	/**********************************/
	/* transient support action hooks */
	/**********************************/
	
	if ( function_exists('BH_acf_save_options') )
		add_action('acf/save_post', 'BH_acf_save_options', 20);

?>